# MySQL Database for local development

services:
  database:
    image: mysql:8.4.5
    container_name: library_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - library_network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local

networks:
  library_network:
    driver: bridge